package br.com.rodpk.gamelist.model.enums;

public enum CategoryEnum {
    
    ACTION("ACTION"),
    ADVENTURE("ADVENTURE"),
    RPG("RPG"),
    FPS("FPS"),
    RACING("RACING"),
    SHOOTER("SHOOTER"),
    STRATEGY("STRATEGY"),
    SPORTS("SPORTS"),
    RTS("REAL-TIME STRATEGY (RTS)"),
    RTT("REAL-TIME TACTICS (RTT)"),
    MULTIPLAYER("MULTIPLAYER"),
    FIGHTING("FIGHTING"),
    SIMULATION("SIMULATION"),
    ROLE_PLAYING("ROLE PLAYING"),
    ARCADE("ARCADE"),
    MMO("MMO"),
    PUZZLE("PUZZLE"),
    MULTI_PLATFORM("MULTI PLATFORM"),
    REALITY("REALITY"),
    MUSIC("MUSIC"),
    ADVENTURE_RPG("ADVENTURE RPG"),
    OPEN_WORLD("OPEN WORLD"),
    INDIE("INDIE"),
    MOBA("MOBA"),
    BOARD_GAME("BOARD GAME"),
    MOBILE("MOBILE"),
    STRATEGY_RPG("STRATEGY RPG"),
    JRPG("JRPG"),
    TURN_BASED("TURN BASED"),
    MULTIPLAYER_RPG("MULTIPLAYER RPG"),
    NACIONAL("NACIONAL"),
    PLATFORM("PLATFORM"),
    BEAT_EM_UP("BEAT'EM UP"),
    STEALTH("STEALTH"),
    SURVIVAL("SURVIVAL"),
    RHYTHM("RHYTHM"),
    VR("VR"),
    BATTLE_ROYALE("BATTLE ROYALE"),
    SURVIVAL_HORROR("SURVIVAL HORROR"),
    METROIDVANIA("METROIDVANIA"),
    VISUAL_NOVEL("VISUAL NOVEL"),
    INTERACTIVE_MOVIE("INTERACTIVE MOVIE"),
    PHYSICS("PHYSICS"),
    CODING("CODING"),
    EXPLORATION("EXPLORATION"),
    SANDBOX("SANDBOX"),
    VEHICLE_SIMULATION("VEHICLE_SIMULATION"),
    TOWER_DEFENSE("TOWER DEFENSE"),
    AUTO_CHESS("AUTO CHESS"),
    COMPETITIVE("COMPETITIVE"),
    TRIVIA("TRIVIA"),
    IDLE_GAME("IDLE GAME"),
    LOGIC_GAME("LOGIC GAME"),
    PARTY_GAME("PARTY GAME"),
    TYPING_GAME("TYPING GAME"),
    EDUCATIONAL_GAME("EDUCATIONAL GAME");





    

    private final String value;

    CategoryEnum (String value) {
        this.value = value;
    }

    public String value() {
        return value;
    }

}
