version: '3'

services:
  gamelist-db:
    image: postgres:11
    container_name: gamelist-db
    restart: always
    environment:
      - POSTGRES_DB=gamelist-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5435:5432
